package net.code.java.hibernate;
// Generated 13 nov. 2018 11:01:02 by Hibernate Tools 5.2.11.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * DssCustomer generated by hbm2java
 */
@Entity
@Table(name = "dss_customer", catalog = "tpcd")
public class DssCustomer implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -6314297009433240368L;
	private int CCustkey;
	private DssNation dssNation;
	private String CName;
	private String CAddress;
	private String CPhone;
	private double CAcctbal;
	private String CMktsegment;
	private String CComment;
	@SuppressWarnings("unused")
	private int stat = 3;
	private Set<DssOrder> dssOrders = new HashSet<DssOrder>(0);

	public DssCustomer() {
	}

	public DssCustomer(int CCustkey, DssNation dssNation, String CName, String CAddress, String CPhone, double CAcctbal,
			String CMktsegment) {
		this.CCustkey = CCustkey;
		this.dssNation = dssNation;
		this.CName = CName;
		this.CAddress = CAddress;
		this.CPhone = CPhone;
		this.CAcctbal = CAcctbal;
		this.CMktsegment = CMktsegment;
	}

	public DssCustomer(int CCustkey, DssNation dssNation, String CName, String CAddress, String CPhone, double CAcctbal,
			String CMktsegment, String CComment, Set<DssOrder> dssOrders) {
		this.CCustkey = CCustkey;
		this.dssNation = dssNation;
		this.CName = CName;
		this.CAddress = CAddress;
		this.CPhone = CPhone;
		this.CAcctbal = CAcctbal;
		this.CMktsegment = CMktsegment;
		this.CComment = CComment;
		this.dssOrders = dssOrders;
	}

	@Id

	@Column(name = "c_custkey", unique = true, nullable = false)
	public int getCCustkey() {
		return this.CCustkey;
	}

	public void setCCustkey(int CCustkey) {
		this.CCustkey = CCustkey;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "c_nationkey", nullable = false)
	public DssNation getDssNation() {
		return this.dssNation;
	}

	public void setDssNation(DssNation dssNation) {
		this.dssNation = dssNation;
	}

	@Column(name = "c_name", nullable = false, length = 25)
	public String getCName() {
		return this.CName;
	}

	public void setCName(String CName) {
		this.CName = CName;
	}

	@Column(name = "c_address", nullable = false, length = 40)
	public String getCAddress() {
		return this.CAddress;
	}

	public void setCAddress(String CAddress) {
		this.CAddress = CAddress;
	}

	@Column(name = "c_phone", nullable = false, length = 15)
	public String getCPhone() {
		return this.CPhone;
	}

	public void setCPhone(String CPhone) {
		this.CPhone = CPhone;
	}

	@Column(name = "c_acctbal", nullable = false, precision = 22, scale = 0)
	public double getCAcctbal() {
		return this.CAcctbal;
	}

	public void setCAcctbal(double CAcctbal) {
		this.CAcctbal = CAcctbal;
	}

	@Column(name = "c_mktsegment", nullable = false, length = 10)
	public String getCMktsegment() {
		return this.CMktsegment;
	}

	public void setCMktsegment(String CMktsegment) {
		this.CMktsegment = CMktsegment;
	}

	@Column(name = "c_comment", length = 117)
	public String getCComment() {
		return this.CComment;
	}

	public void setCComment(String CComment) {
		this.CComment = CComment;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "dssCustomer")
	public Set<DssOrder> getDssOrders() {
		return this.dssOrders;
	}

	public void setDssOrders(Set<DssOrder> dssOrders) {
		this.dssOrders = dssOrders;
	}

}
