package net.code.java.hibernate;
// Generated 13 nov. 2018 11:01:02 by Hibernate Tools 5.2.11.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * DssLineitemId generated by hbm2java
 */
@Embeddable
public class DssLineitemId implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -2878126872363843239L;
	private long LOrderkey;
	private int LLinenumber;

	public DssLineitemId() {
	}

	public DssLineitemId(long LOrderkey, int LLinenumber) {
		this.LOrderkey = LOrderkey;
		this.LLinenumber = LLinenumber;
	}

	@Column(name = "l_orderkey", nullable = false, precision = 18, scale = 0)
	public long getLOrderkey() {
		return this.LOrderkey;
	}

	public void setLOrderkey(long LOrderkey) {
		this.LOrderkey = LOrderkey;
	}

	@Column(name = "l_linenumber", nullable = false)
	public int getLLinenumber() {
		return this.LLinenumber;
	}

	public void setLLinenumber(int LLinenumber) {
		this.LLinenumber = LLinenumber;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof DssLineitemId))
			return false;
		DssLineitemId castOther = (DssLineitemId) other;

		return (this.getLOrderkey() == castOther.getLOrderkey())
				&& (this.getLLinenumber() == castOther.getLLinenumber());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (int) this.getLOrderkey();
		result = 37 * result + this.getLLinenumber();
		return result;
	}

}
