package net.code.java.hibernate;
// Generated 13 nov. 2018 11:01:02 by Hibernate Tools 5.2.11.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * DssNation generated by hbm2java
 */
@Entity
@Table(name = "dss_nation", catalog = "tpcd")
public class DssNation implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1327425040604179138L;
	private int NNationkey;
	private DssRegion dssRegion;
	private String NName;
	private String NComment;
	private Set<DssCustomer> dssCustomers = new HashSet<DssCustomer>(0);
	private Set<DssSupplier> dssSuppliers = new HashSet<DssSupplier>(0);

	public DssNation() {
	}

	public DssNation(int NNationkey, DssRegion dssRegion, String NName) {
		this.NNationkey = NNationkey;
		this.dssRegion = dssRegion;
		this.NName = NName;
	}

	public DssNation(int NNationkey, DssRegion dssRegion, String NName, String NComment, Set<DssCustomer> dssCustomers,
			Set<DssSupplier> dssSuppliers) {
		this.NNationkey = NNationkey;
		this.dssRegion = dssRegion;
		this.NName = NName;
		this.NComment = NComment;
		this.dssCustomers = dssCustomers;
		this.dssSuppliers = dssSuppliers;
	}

	@Id

	@Column(name = "n_nationkey", unique = true, nullable = false)
	public int getNNationkey() {
		return this.NNationkey;
	}

	public void setNNationkey(int NNationkey) {
		this.NNationkey = NNationkey;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "n_regionkey", nullable = false)
	public DssRegion getDssRegion() {
		return this.dssRegion;
	}

	public void setDssRegion(DssRegion dssRegion) {
		this.dssRegion = dssRegion;
	}

	@Column(name = "n_name", nullable = false, length = 25)
	public String getNName() {
		return this.NName;
	}

	public void setNName(String NName) {
		this.NName = NName;
	}

	@Column(name = "n_comment", length = 152)
	public String getNComment() {
		return this.NComment;
	}

	public void setNComment(String NComment) {
		this.NComment = NComment;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "dssNation")
	public Set<DssCustomer> getDssCustomers() {
		return this.dssCustomers;
	}

	public void setDssCustomers(Set<DssCustomer> dssCustomers) {
		this.dssCustomers = dssCustomers;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "dssNation")
	public Set<DssSupplier> getDssSuppliers() {
		return this.dssSuppliers;
	}

	public void setDssSuppliers(Set<DssSupplier> dssSuppliers) {
		this.dssSuppliers = dssSuppliers;
	}

}
