package net.code.java.hibernate;
// Generated 13 nov. 2018 11:01:02 by Hibernate Tools 5.2.11.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * DssOrder generated by hbm2java
 */
@Entity
@Table(name = "dss_order", catalog = "tpcd")
public class DssOrder implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -9129988882237047202L;
	private long OOrderkey;
	private DssCustomer dssCustomer;
	private char OOrderstatus;
	private double OTotalprice;
	private Date OOrderdate;
	private String OOrderpriority;
	private String OClerk;
	private int OShippriority;
	private String OComment;
	private Set<DssLineitem> dssLineitems = new HashSet<DssLineitem>(0);

	public DssOrder() {
	}

	public DssOrder(long OOrderkey, DssCustomer dssCustomer, char OOrderstatus, double OTotalprice,
			String OOrderpriority, String OClerk, int OShippriority) {
		this.OOrderkey = OOrderkey;
		this.dssCustomer = dssCustomer;
		this.OOrderstatus = OOrderstatus;
		this.OTotalprice = OTotalprice;
		this.OOrderpriority = OOrderpriority;
		this.OClerk = OClerk;
		this.OShippriority = OShippriority;
	}

	public DssOrder(long OOrderkey, DssCustomer dssCustomer, char OOrderstatus, double OTotalprice, Date OOrderdate,
			String OOrderpriority, String OClerk, int OShippriority, String OComment, Set<DssLineitem> dssLineitems) {
		this.OOrderkey = OOrderkey;
		this.dssCustomer = dssCustomer;
		this.OOrderstatus = OOrderstatus;
		this.OTotalprice = OTotalprice;
		this.OOrderdate = OOrderdate;
		this.OOrderpriority = OOrderpriority;
		this.OClerk = OClerk;
		this.OShippriority = OShippriority;
		this.OComment = OComment;
		this.dssLineitems = dssLineitems;
	}

	@Id

	@Column(name = "o_orderkey", unique = true, nullable = false, precision = 18, scale = 0)
	public long getOOrderkey() {
		return this.OOrderkey;
	}

	public void setOOrderkey(long OOrderkey) {
		this.OOrderkey = OOrderkey;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "o_custkey", nullable = false)
	public DssCustomer getDssCustomer() {
		return this.dssCustomer;
	}

	public void setDssCustomer(DssCustomer dssCustomer) {
		this.dssCustomer = dssCustomer;
	}

	@Column(name = "o_orderstatus", nullable = false, length = 1)
	public char getOOrderstatus() {
		return this.OOrderstatus;
	}

	public void setOOrderstatus(char OOrderstatus) {
		this.OOrderstatus = OOrderstatus;
	}

	@Column(name = "o_totalprice", nullable = false, precision = 22, scale = 0)
	public double getOTotalprice() {
		return this.OTotalprice;
	}

	public void setOTotalprice(double OTotalprice) {
		this.OTotalprice = OTotalprice;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "o_orderdate", length = 10)
	public Date getOOrderdate() {
		return this.OOrderdate;
	}

	public void setOOrderdate(Date OOrderdate) {
		this.OOrderdate = OOrderdate;
	}

	@Column(name = "o_orderpriority", nullable = false, length = 15)
	public String getOOrderpriority() {
		return this.OOrderpriority;
	}

	public void setOOrderpriority(String OOrderpriority) {
		this.OOrderpriority = OOrderpriority;
	}

	@Column(name = "o_clerk", nullable = false, length = 15)
	public String getOClerk() {
		return this.OClerk;
	}

	public void setOClerk(String OClerk) {
		this.OClerk = OClerk;
	}

	@Column(name = "o_shippriority", nullable = false)
	public int getOShippriority() {
		return this.OShippriority;
	}

	public void setOShippriority(int OShippriority) {
		this.OShippriority = OShippriority;
	}

	@Column(name = "o_comment", length = 79)
	public String getOComment() {
		return this.OComment;
	}

	public void setOComment(String OComment) {
		this.OComment = OComment;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "dssOrder")
	public Set<DssLineitem> getDssLineitems() {
		return this.dssLineitems;
	}

	public void setDssLineitems(Set<DssLineitem> dssLineitems) {
		this.dssLineitems = dssLineitems;
	}

}
