package net.code.java.hibernate;
// Generated 13 nov. 2018 11:01:02 by Hibernate Tools 5.2.11.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * DssPartsuppId generated by hbm2java
 */
@Embeddable
public class DssPartsuppId implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 8547495090479726811L;
	private int psPartkey;
	private int psSuppkey;

	public DssPartsuppId() {
	}

	public DssPartsuppId(int psPartkey, int psSuppkey) {
		this.psPartkey = psPartkey;
		this.psSuppkey = psSuppkey;
	}

	@Column(name = "ps_partkey", nullable = false)
	public int getPsPartkey() {
		return this.psPartkey;
	}

	public void setPsPartkey(int psPartkey) {
		this.psPartkey = psPartkey;
	}

	@Column(name = "ps_suppkey", nullable = false)
	public int getPsSuppkey() {
		return this.psSuppkey;
	}

	public void setPsSuppkey(int psSuppkey) {
		this.psSuppkey = psSuppkey;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof DssPartsuppId))
			return false;
		DssPartsuppId castOther = (DssPartsuppId) other;

		return (this.getPsPartkey() == castOther.getPsPartkey()) && (this.getPsSuppkey() == castOther.getPsSuppkey());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getPsPartkey();
		result = 37 * result + this.getPsSuppkey();
		return result;
	}

}
