package net.code.java.hibernate;
// Generated 13 nov. 2018 11:01:02 by Hibernate Tools 5.2.11.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToOne;
import javax.persistence.PrimaryKeyJoinColumn;
import javax.persistence.Table;

/**
 * DssPartsupp generated by hbm2java
 */
@Entity
@Table(name = "dss_partsupp", catalog = "tpcd")
public class DssPartsupp implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -7643363026038262169L;
	private DssPartsuppId id;
	private DssLineitem dssLineitem;
	private DssPart dssPart;
	private DssSupplier dssSupplier;
	private int psAvailqty;
	private double psSupplycost;
	private String psComment;

	public DssPartsupp() {
	}

	public DssPartsupp(DssLineitem dssLineitem, DssPart dssPart, DssSupplier dssSupplier, int psAvailqty,
			double psSupplycost) {
		this.dssLineitem = dssLineitem;
		this.dssPart = dssPart;
		this.dssSupplier = dssSupplier;
		this.psAvailqty = psAvailqty;
		this.psSupplycost = psSupplycost;
	}

	public DssPartsupp(DssLineitem dssLineitem, DssPart dssPart, DssSupplier dssSupplier, int psAvailqty,
			double psSupplycost, String psComment) {
		this.dssLineitem = dssLineitem;
		this.dssPart = dssPart;
		this.dssSupplier = dssSupplier;
		this.psAvailqty = psAvailqty;
		this.psSupplycost = psSupplycost;
		this.psComment = psComment;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "psPartkey", column = @Column(name = "ps_partkey", nullable = false)),
			@AttributeOverride(name = "psSuppkey", column = @Column(name = "ps_suppkey", nullable = false)) })
	public DssPartsuppId getId() {
		return this.id;
	}

	public void setId(DssPartsuppId id) {
		this.id = id;
	}

	@OneToOne(fetch = FetchType.LAZY)
	@PrimaryKeyJoinColumn
	public DssLineitem getDssLineitem() {
		return this.dssLineitem;
	}

	public void setDssLineitem(DssLineitem dssLineitem) {
		this.dssLineitem = dssLineitem;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ps_partkey", nullable = false, insertable = false, updatable = false)
	public DssPart getDssPart() {
		return this.dssPart;
	}

	public void setDssPart(DssPart dssPart) {
		this.dssPart = dssPart;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ps_suppkey", nullable = false, insertable = false, updatable = false)
	public DssSupplier getDssSupplier() {
		return this.dssSupplier;
	}

	public void setDssSupplier(DssSupplier dssSupplier) {
		this.dssSupplier = dssSupplier;
	}

	@Column(name = "ps_availqty", nullable = false)
	public int getPsAvailqty() {
		return this.psAvailqty;
	}

	public void setPsAvailqty(int psAvailqty) {
		this.psAvailqty = psAvailqty;
	}

	@Column(name = "ps_supplycost", nullable = false, precision = 22, scale = 0)
	public double getPsSupplycost() {
		return this.psSupplycost;
	}

	public void setPsSupplycost(double psSupplycost) {
		this.psSupplycost = psSupplycost;
	}

	@Column(name = "ps_comment", length = 199)
	public String getPsComment() {
		return this.psComment;
	}

	public void setPsComment(String psComment) {
		this.psComment = psComment;
	}

}
