package net.code.java.hibernate;
// Generated 13 nov. 2018 11:01:02 by Hibernate Tools 5.2.11.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * DssRegion generated by hbm2java
 */
@Entity
@Table(name = "dss_region", catalog = "tpcd")
public class DssRegion implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 8021442284544856060L;
	private int RRegionkey;
	private String RName;
	private String RComment;
	private Set<DssNation> dssNations = new HashSet<DssNation>(0);

	public DssRegion() {
	}

	public DssRegion(int RRegionkey, String RName) {
		this.RRegionkey = RRegionkey;
		this.RName = RName;
	}

	public DssRegion(int RRegionkey, String RName, String RComment, Set<DssNation> dssNations) {
		this.RRegionkey = RRegionkey;
		this.RName = RName;
		this.RComment = RComment;
		this.dssNations = dssNations;
	}

	@Id

	@Column(name = "r_regionkey", unique = true, nullable = false)
	public int getRRegionkey() {
		return this.RRegionkey;
	}

	public void setRRegionkey(int RRegionkey) {
		this.RRegionkey = RRegionkey;
	}

	@Column(name = "r_name", nullable = false, length = 25)
	public String getRName() {
		return this.RName;
	}

	public void setRName(String RName) {
		this.RName = RName;
	}

	@Column(name = "r_comment", length = 152)
	public String getRComment() {
		return this.RComment;
	}

	public void setRComment(String RComment) {
		this.RComment = RComment;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "dssRegion")
	public Set<DssNation> getDssNations() {
		return this.dssNations;
	}

	public void setDssNations(Set<DssNation> dssNations) {
		this.dssNations = dssNations;
	}

}
